# Generated by Django 5.0.3 on 2024-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(blank=True, max_length=255, null=True)),
                ('interior_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('insuhos_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('offedu_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('trvlec_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('fsbz_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('svcarc_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('dist_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('plsanit_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('clothgds_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('auto_am', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
        ),
    ]
