# Generated by Django 5.0.3 on 2024-05-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customercardhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercardhistory',
            name='car_price',
        ),
    ]
