# Generated by Django 5.0.3 on 2024-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_predict_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_rate_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('min_rate', models.FloatField()),
                ('max_rate', models.FloatField()),
                ('pq_avg_act_rate', models.FloatField()),
                ('erc_rate', models.CharField(max_length=255)),
                ('late_payment_rate', models.CharField(max_length=255)),
                ('reference_date', models.DateField()),
                ('credit_range', models.IntegerField()),
                ('loan_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='scoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_status', models.BooleanField()),
                ('home_ownership', models.CharField(max_length=255)),
                ('loan_amnt', models.IntegerField()),
                ('int_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('term', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('annual_inc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dti', models.DecimalField(decimal_places=2, max_digits=7)),
                ('avg_cur_bal', models.IntegerField()),
                ('acc_open_past_24mths', models.IntegerField()),
                ('total_bc_limit', models.IntegerField()),
                ('bc_util', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
