# Generated by Django 5.0.3 on 2024-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_loan_rate_list_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_rate_list',
            name='pq_avg_act_rate',
            field=models.CharField(max_length=255),
        ),
    ]
