# Generated by Django 5.0.3 on 2024-04-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='L_NAME',
            field=models.TextField(null=True),
        ),
    ]
