# Generated by Django 5.0.3 on 2024-05-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_customercardhistory_car_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCardHistory',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='test_sangmin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='common.predict_budget'),
        ),
        migrations.DeleteModel(
            name='TestSangmin',
        ),
    ]
