# Generated by Django 5.0.3 on 2024-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_loan_rate_list_pq_avg_act_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_rate_list',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
