# Generated by Django 5.0.3 on 2024-04-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_loan_rate_list_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAPI',
            fields=[
                ('SEQ', models.IntegerField()),
                ('MNAME', models.TextField()),
                ('PRICE', models.IntegerField()),
                ('MYERAR', models.IntegerField()),
                ('MILEAGE', models.IntegerField()),
                ('COLOR', models.TextField()),
                ('TRANS', models.TextField()),
                ('F_TYPE', models.TextField()),
                ('DISP', models.IntegerField()),
                ('VTYPE', models.TextField()),
                ('VNUM', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CU_HIS', models.IntegerField()),
                ('MVD_HIS', models.FloatField()),
                ('AVD_HIS', models.FloatField()),
                ('FD_HIS', models.IntegerField()),
                ('VT_HIS', models.FloatField()),
                ('US_HIS', models.IntegerField()),
                ('L_NAME', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='SEQ',
        ),
        migrations.AddField(
            model_name='car',
            name='seq',
            field=models.TextField(null=True),
        ),
    ]
