# Generated by Django 5.0.3 on 2024-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_loan_rate_list_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='avg_fico',
            field=models.DecimalField(decimal_places=1, default=650.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='late_avg_fico',
            field=models.DecimalField(decimal_places=1, default=650.0, max_digits=4),
            preserve_default=False,
        ),
    ]
