# Generated by Django 5.0.3 on 2024-04-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_scoring_avg_fico_scoring_late_avg_fico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoring',
            old_name='late_avg_fico',
            new_name='last_avg_fico',
        ),
    ]
