# Generated by Django 5.0.3 on 2024-04-09 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSalesPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('MNAME', models.TextField()),
                ('MYERAR', models.IntegerField()),
                ('MILEAGE', models.IntegerField()),
                ('COLOR', models.TextField()),
                ('TRANS', models.TextField()),
                ('F_TYPE', models.TextField()),
                ('DISP', models.IntegerField()),
                ('VTYPE', models.TextField()),
                ('VNUM', models.CharField(max_length=100)),
                ('CU_HIS', models.IntegerField()),
                ('MVD_HIS', models.FloatField()),
                ('AVD_HIS', models.FloatField()),
                ('FD_HIS', models.IntegerField()),
                ('VT_HIS', models.FloatField()),
                ('US_HIS', models.IntegerField()),
                ('PRICE', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('buyer', models.ManyToManyField(related_name='buyer_car_sales_posts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
