# Generated by Django 5.0.3 on 2024-04-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedimage', models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media')),
                ('processedimage', models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media')),
                ('has_car', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pybo_uploadedimage2',
                'managed': True,
            },
        ),
    ]
