# Generated by Django 5.0.3 on 2024-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('buyer_price', models.IntegerField()),
            ],
            options={
                'db_table': 'BuyerMessages',
                'managed': True,
            },
        ),
    ]
