# Generated by Django 5.0.3 on 2024-05-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage2',
        ),
    ]
