# Generated by Django 5.0.3 on 2024-04-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image1',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image2',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image3',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image4',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='processedimage',
            field=models.ImageField(upload_to='C:\\Users\\CHK\\Desktop\\django_migration\\ourcar_Django\\final_project\\_media'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='uploadedimage',
            field=models.ImageField(upload_to='C:\\Users\\CHK\\Desktop\\django_migration\\ourcar_Django\\final_project\\_media'),
        ),
    ]
