# Generated by Django 5.0.3 on 2024-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_carsalespost_detected_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsalespost',
            name='detected_image1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsalespost',
            name='detected_image2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsalespost',
            name='detected_image3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsalespost',
            name='detected_image4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsalespost',
            name='detected_thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
