# Generated by Django 5.0.3 on 2024-04-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_uploadedimage2'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalespost',
            name='brand',
            field=models.TextField(null=True),
        ),
    ]
