# Generated by Django 5.0.3 on 2024-04-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_buyermessages'),
        ('sales', '0004_alter_carsalespost_detected_image1_and_more'),
    ]

    operations = [
    ]
