# Generated by Django 5.0.3 on 2024-04-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_merge_20240422_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalespost',
            name='buyers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='processedimage',
            field=models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='uploadedimage',
            field=models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media'),
        ),
    ]
