# Generated by Django 5.0.3 on 2024-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_carsalespost_buyers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermessages',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
