# Generated by Django 5.0.3 on 2024-04-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_buyermessages_buyer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyermessages',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='buyermessages',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='buyermessages',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
