# Generated by Django 5.0.3 on 2024-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_buyer_id_buyermessages_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalespost',
            name='make_deal',
            field=models.BooleanField(default=False),
        ),
    ]
