# Generated by Django 5.0.3 on 2024-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_carsalespost_make_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalespost',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='Image6',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='Image7',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='Image8',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image5',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image6',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image7',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AddField(
            model_name='carsalespost',
            name='detected_image8',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='processedimage',
            field=models.ImageField(upload_to='C:\\Users\\CHK\\Desktop\\Final_django\\final_project\\_media'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='uploadedimage',
            field=models.ImageField(upload_to='C:\\Users\\CHK\\Desktop\\Final_django\\final_project\\_media'),
        ),
    ]
