# Generated by Django 5.0.3 on 2024-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_uploadedimage2_processedimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage2',
            name='processedimage',
            field=models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media'),
        ),
        migrations.AlterField(
            model_name='uploadedimage2',
            name='uploadedimage',
            field=models.ImageField(upload_to='C:\\Users\\SANGMIN\\Desktop\\fisa_final_ourcar\\final_project\\_media'),
        ),
    ]
