# Generated by Django 5.0.3 on 2024-04-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_testsangmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSangmin',
        ),
    ]
